"""added notify column to Subscription table

Revision ID: 161df9d36eca
Revises: ef77ff2bb3a3
Create Date: 2024-10-25 18:52:18.350079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "161df9d36eca"
down_revision = "ef77ff2bb3a3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("subscriptions", sa.Column("notify", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("subscriptions", "notify")
    # ### end Alembic commands ###
