"""added Gym table

Revision ID: 85fbd7f6d3a9
Revises: 7172fe03a656
Create Date: 2024-10-19 01:21:39.840799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85fbd7f6d3a9'
down_revision = '7172fe03a656'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gyms',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gyms'))
    )
    op.add_column('subscriptions', sa.Column('gym_id', sa.Integer(), nullable=False))
    op.create_foreign_key(op.f('fk_subscriptions_gym_id_gyms'), 'subscriptions', 'gyms', ['gym_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_subscriptions_gym_id_gyms'), 'subscriptions', type_='foreignkey')
    op.drop_column('subscriptions', 'gym_id')
    op.drop_table('gyms')
    # ### end Alembic commands ###
