"""added notify column to Subscription

Revision ID: 213806c6185f
Revises: ef77ff2bb3a3
Create Date: 2024-10-26 00:26:04.212230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '213806c6185f'
down_revision = 'ef77ff2bb3a3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('notify', sa.Boolean(), server_default='False', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'notify')
    # ### end Alembic commands ###
